name: Run "批准" Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *'   # 每2小時執行一次
  workflow_dispatch:        # 允許手動觸發

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 指定你使用的 Python 版本，例如 '3.11'

      - name: Restore sent_announcements.txt
        uses: actions/download-artifact@v4
        with:
          name: sent_announcements
          path: ./sent_announcements.txt  # 指定下載的檔案路徑

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the script
        run: |
          python get_new_biotech_ann.py   # 執行你的 Python 腳本

      - name: Save sent_announcements.txt
        uses: actions/upload-artifact@v4
        with:
          name: sent_announcements
          path: sent_announcements.txt  # 指定要上傳的檔案

